# Site settings
title: 황인성
email: dev.insung.hwang@gmail.com
url: https://insung.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Web Developer"
meta_author: 황인성

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 828282 #18bc9c #80B3FF
  primary-rgb: "116,168,220" #"24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: insung hwang
  location: 우리집
  social: Github & Bitbucket
  credits: 크레딧

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/insung
  - title: bitbucket
    url: https://bitbucket.org/insunghwang  
  - title: twitter
    url: http://twitter.com/imissyoubrad

# Postal address (add as many lines as necessary)
address:
  - line: 서울시 서대문구 북가좌동

# Credits content
credits: 'Start Bootstrap 사이트의 <a href="https://startbootstrap.com/template-overviews/freelancer/">Freelancer theme</a> 를 사용하였습니다.'

# Build settings
markdown: kramdown
permalink: pretty
